// altera_jesd204_0002.v

// This file was auto-generated from altera_jesd204_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 14.0 200 at 2014.07.17.13:20:14

`timescale 1 ps / 1 ps
module altera_jesd204_0002 #(
		parameter DEVICE_FAMILY            = "Arria V",
		parameter SUBCLASSV                = 1,
		parameter PCS_CONFIG               = "JESD_PCS_CFG1",
		parameter L                        = 2,
		parameter M                        = 2,
		parameter F                        = 2,
		parameter N                        = 14,
		parameter N_PRIME                  = 16,
		parameter S                        = 1,
		parameter K                        = 32,
		parameter SCR                      = 1,
		parameter CS                       = 0,
		parameter CF                       = 0,
		parameter HD                       = 0,
		parameter ECC_EN                   = 1,
		parameter DLB_TEST                 = 0,
		parameter PHADJ                    = 0,
		parameter ADJCNT                   = 0,
		parameter ADJDIR                   = 0,
		parameter OPTIMIZE                 = 0,
		parameter DID                      = 0,
		parameter BID                      = 0,
		parameter LID0                     = 0,
		parameter FCHK0                    = 65,
		parameter LID1                     = 1,
		parameter FCHK1                    = 66,
		parameter LID2                     = 2,
		parameter FCHK2                    = 0,
		parameter LID3                     = 3,
		parameter FCHK3                    = 0,
		parameter LID4                     = 4,
		parameter FCHK4                    = 0,
		parameter LID5                     = 5,
		parameter FCHK5                    = 0,
		parameter LID6                     = 6,
		parameter FCHK6                    = 0,
		parameter LID7                     = 7,
		parameter FCHK7                    = 0,
		parameter JESDV                    = 1,
		parameter PMA_WIDTH                = 32,
		parameter SER_SIZE                 = 4,
		parameter FK                       = 64,
		parameter RES1                     = 0,
		parameter RES2                     = 0,
		parameter BIT_REVERSAL             = 0,
		parameter BYTE_REVERSAL            = 0,
		parameter ALIGNMENT_PATTERN        = 658812,
		parameter PULSE_WIDTH              = 2,
		parameter LS_FIFO_DEPTH            = 32,
		parameter LS_FIFO_WIDTHU           = 5,
		parameter UNUSED_TX_PARALLEL_WIDTH = 8,
		parameter UNUSED_RX_PARALLEL_WIDTH = 8,
		parameter XCVR_PLL_LOCKED_WIDTH    = 1
	) (
		input  wire         tx_pll_ref_clk,             //            tx_pll_ref_clk.clk
		input  wire         txlink_clk,                 //                txlink_clk.clk
		input  wire         txlink_rst_n_reset_n,       //              txlink_rst_n.reset_n
		input  wire         jesd204_tx_avs_clk,         //        jesd204_tx_avs_clk.clk
		input  wire         jesd204_tx_avs_rst_n,       //      jesd204_tx_avs_rst_n.reset_n
		input  wire         jesd204_tx_avs_chipselect,  //            jesd204_tx_avs.chipselect
		input  wire [7:0]   jesd204_tx_avs_address,     //                          .address
		input  wire         jesd204_tx_avs_read,        //                          .read
		output wire [31:0]  jesd204_tx_avs_readdata,    //                          .readdata
		output wire         jesd204_tx_avs_waitrequest, //                          .waitrequest
		input  wire         jesd204_tx_avs_write,       //                          .write
		input  wire [31:0]  jesd204_tx_avs_writedata,   //                          .writedata
		input  wire [63:0]  jesd204_tx_link_data,       //           jesd204_tx_link.data
		input  wire         jesd204_tx_link_valid,      //                          .valid
		output wire         jesd204_tx_link_ready,      //                          .ready
		output wire         jesd204_tx_int,             //            jesd204_tx_int.export
		input  wire         tx_sysref,                  //                 tx_sysref.export
		input  wire         sync_n,                     //                    sync_n.export
		output wire         tx_dev_sync_n,              //             tx_dev_sync_n.export
		input  wire         mdev_sync_n,                //               mdev_sync_n.export
		output wire         jesd204_tx_frame_ready,     //    jesd204_tx_frame_ready.export
		output wire [4:0]   tx_csr_l,                   //                  tx_csr_l.export
		output wire [7:0]   tx_csr_f,                   //                  tx_csr_f.export
		output wire [4:0]   tx_csr_k,                   //                  tx_csr_k.export
		output wire [7:0]   tx_csr_m,                   //                  tx_csr_m.export
		output wire [1:0]   tx_csr_cs,                  //                 tx_csr_cs.export
		output wire [4:0]   tx_csr_n,                   //                  tx_csr_n.export
		output wire [4:0]   tx_csr_np,                  //                 tx_csr_np.export
		output wire [4:0]   tx_csr_s,                   //                  tx_csr_s.export
		output wire         tx_csr_hd,                  //                 tx_csr_hd.export
		output wire [4:0]   tx_csr_cf,                  //                 tx_csr_cf.export
		output wire [1:0]   tx_csr_lane_powerdown,      //     tx_csr_lane_powerdown.export
		output wire [3:0]   csr_tx_testmode,            //           csr_tx_testmode.export
		output wire [31:0]  csr_tx_testpattern_a,       //      csr_tx_testpattern_a.export
		output wire [31:0]  csr_tx_testpattern_b,       //      csr_tx_testpattern_b.export
		output wire [31:0]  csr_tx_testpattern_c,       //      csr_tx_testpattern_c.export
		output wire [31:0]  csr_tx_testpattern_d,       //      csr_tx_testpattern_d.export
		input  wire         jesd204_tx_frame_error,     //    jesd204_tx_frame_error.export
		output wire [63:0]  jesd204_tx_dlb_data,        //       jesd204_tx_dlb_data.export
		output wire [7:0]   jesd204_tx_dlb_kchar_data,  // jesd204_tx_dlb_kchar_data.export
		output wire [1:0]   txphy_clk,                  //                 txphy_clk.tx_std_clkout
		output wire [1:0]   tx_serial_data,             //            tx_serial_data.tx_serial_data
		input  wire [0:0]   pll_powerdown,              //             pll_powerdown.pll_powerdown
		input  wire [1:0]   tx_analogreset,             //            tx_analogreset.tx_analogreset
		input  wire [1:0]   tx_digitalreset,            //           tx_digitalreset.tx_digitalreset
		output wire [1:0]   pll_locked,                 //                pll_locked.export
		output wire [1:0]   tx_cal_busy,                //               tx_cal_busy.export
		input  wire         rx_pll_ref_clk,             //            rx_pll_ref_clk.clk
		input  wire         rxlink_clk,                 //                rxlink_clk.clk
		input  wire         rxlink_rst_n_reset_n,       //              rxlink_rst_n.reset_n
		input  wire         jesd204_rx_avs_clk,         //        jesd204_rx_avs_clk.clk
		input  wire         jesd204_rx_avs_rst_n,       //      jesd204_rx_avs_rst_n.reset_n
		input  wire         jesd204_rx_avs_chipselect,  //            jesd204_rx_avs.chipselect
		input  wire [7:0]   jesd204_rx_avs_address,     //                          .address
		input  wire         jesd204_rx_avs_read,        //                          .read
		output wire [31:0]  jesd204_rx_avs_readdata,    //                          .readdata
		output wire         jesd204_rx_avs_waitrequest, //                          .waitrequest
		input  wire         jesd204_rx_avs_write,       //                          .write
		input  wire [31:0]  jesd204_rx_avs_writedata,   //                          .writedata
		output wire [63:0]  jesd204_rx_link_data,       //           jesd204_rx_link.data
		output wire         jesd204_rx_link_valid,      //                          .valid
		input  wire         jesd204_rx_link_ready,      //                          .ready
		input  wire [63:0]  jesd204_rx_dlb_data,        //       jesd204_rx_dlb_data.export
		input  wire [1:0]   jesd204_rx_dlb_data_valid,  // jesd204_rx_dlb_data_valid.export
		input  wire [7:0]   jesd204_rx_dlb_kchar_data,  // jesd204_rx_dlb_kchar_data.export
		input  wire [7:0]   jesd204_rx_dlb_errdetect,   //  jesd204_rx_dlb_errdetect.export
		input  wire [7:0]   jesd204_rx_dlb_disperr,     //    jesd204_rx_dlb_disperr.export
		input  wire         alldev_lane_aligned,        //       alldev_lane_aligned.export
		input  wire         rx_sysref,                  //                 rx_sysref.export
		input  wire         jesd204_rx_frame_error,     //    jesd204_rx_frame_error.export
		output wire         jesd204_rx_int,             //            jesd204_rx_int.export
		output wire [3:0]   csr_rx_testmode,            //           csr_rx_testmode.export
		output wire         dev_lane_aligned,           //          dev_lane_aligned.export
		output wire         rx_dev_sync_n,              //             rx_dev_sync_n.export
		output wire [3:0]   rx_sof,                     //                    rx_sof.export
		output wire [3:0]   rx_somf,                    //                   rx_somf.export
		output wire [7:0]   rx_csr_f,                   //                  rx_csr_f.export
		output wire [4:0]   rx_csr_k,                   //                  rx_csr_k.export
		output wire [4:0]   rx_csr_l,                   //                  rx_csr_l.export
		output wire [7:0]   rx_csr_m,                   //                  rx_csr_m.export
		output wire [4:0]   rx_csr_n,                   //                  rx_csr_n.export
		output wire [4:0]   rx_csr_s,                   //                  rx_csr_s.export
		output wire [4:0]   rx_csr_cf,                  //                 rx_csr_cf.export
		output wire [1:0]   rx_csr_cs,                  //                 rx_csr_cs.export
		output wire         rx_csr_hd,                  //                 rx_csr_hd.export
		output wire [4:0]   rx_csr_np,                  //                 rx_csr_np.export
		output wire [1:0]   rx_csr_lane_powerdown,      //     rx_csr_lane_powerdown.export
		output wire [1:0]   rxphy_clk,                  //                 rxphy_clk.rx_std_clkout
		input  wire [1:0]   rx_serial_data,             //            rx_serial_data.rx_serial_data
		input  wire [1:0]   rx_analogreset,             //            rx_analogreset.rx_analogreset
		input  wire [1:0]   rx_digitalreset,            //           rx_digitalreset.rx_digitalreset
		input  wire [209:0] reconfig_to_xcvr,           //          reconfig_to_xcvr.reconfig_to_xcvr
		output wire [137:0] reconfig_from_xcvr,         //        reconfig_from_xcvr.reconfig_from_xcvr
		output wire [1:0]   rx_islockedtodata,          //         rx_islockedtodata.export
		output wire [1:0]   rx_cal_busy,                //               rx_cal_busy.export
		input  wire [1:0]   rx_seriallpbken             //           rx_seriallpbken.rx_seriallpbken
	);

	wire   [1:0] inst_tx_csr_lane_polarity_export;          // inst_tx:csr_lane_polarity -> inst_phy:tx_csr_lane_polarity
	wire         inst_tx_csr_bit_reversal_export;           // inst_tx:csr_bit_reversal -> inst_phy:tx_csr_bit_reversal
	wire         inst_tx_csr_byte_reversal_export;          // inst_tx:csr_byte_reversal -> inst_phy:tx_csr_byte_reversal
	wire   [1:0] inst_phy_phy_csr_tx_pcfifo_full_export;    // inst_phy:phy_csr_tx_pcfifo_full -> inst_tx:phy_csr_tx_pcfifo_full
	wire   [1:0] inst_phy_phy_csr_tx_pcfifo_empty_export;   // inst_phy:phy_csr_tx_pcfifo_empty -> inst_tx:phy_csr_tx_pcfifo_empty
	wire   [1:0] inst_tx_phy_tx_elecidle_export;            // inst_tx:phy_tx_elecidle -> inst_phy:phy_tx_elecidle
	wire  [63:0] inst_phy_jesd204_rx_pcs_data_export;       // inst_phy:jesd204_rx_pcs_data -> inst_rx:jesd204_rx_pcs_data
	wire   [1:0] inst_phy_jesd204_rx_pcs_data_valid_export; // inst_phy:jesd204_rx_pcs_data_valid -> inst_rx:jesd204_rx_pcs_data_valid
	wire   [7:0] inst_phy_jesd204_rx_pcs_kchar_data_export; // inst_phy:jesd204_rx_pcs_kchar_data -> inst_rx:jesd204_rx_pcs_kchar_data
	wire   [7:0] inst_phy_jesd204_rx_pcs_errdetect_export;  // inst_phy:jesd204_rx_pcs_errdetect -> inst_rx:jesd204_rx_pcs_errdetect
	wire   [7:0] inst_phy_jesd204_rx_pcs_disperr_export;    // inst_phy:jesd204_rx_pcs_disperr -> inst_rx:jesd204_rx_pcs_disperr
	wire   [1:0] inst_rx_csr_lane_polarity_export;          // inst_rx:csr_lane_polarity -> inst_phy:rx_csr_lane_polarity
	wire         inst_rx_csr_bit_reversal_export;           // inst_rx:csr_bit_reversal -> inst_phy:rx_csr_bit_reversal
	wire         inst_rx_csr_byte_reversal_export;          // inst_rx:csr_byte_reversal -> inst_phy:rx_csr_byte_reversal
	wire   [1:0] inst_rx_patternalign_en_export;            // inst_rx:patternalign_en -> inst_phy:patternalign_en
	wire   [1:0] inst_phy_phy_csr_rx_pcfifo_full_export;    // inst_phy:phy_csr_rx_pcfifo_full -> inst_rx:phy_csr_rx_pcfifo_full
	wire   [1:0] inst_phy_phy_csr_rx_pcfifo_empty_export;   // inst_phy:phy_csr_rx_pcfifo_empty -> inst_rx:phy_csr_rx_pcfifo_empty

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (DEVICE_FAMILY != "Arria V")
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					device_family_check ( .error(1'b1) );
		end
		if (SUBCLASSV != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					subclassv_check ( .error(1'b1) );
		end
		if (PCS_CONFIG != "JESD_PCS_CFG1")
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					pcs_config_check ( .error(1'b1) );
		end
		if (L != 2)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					l_check ( .error(1'b1) );
		end
		if (M != 2)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					m_check ( .error(1'b1) );
		end
		if (F != 2)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					f_check ( .error(1'b1) );
		end
		if (N != 14)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					n_check ( .error(1'b1) );
		end
		if (N_PRIME != 16)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					n_prime_check ( .error(1'b1) );
		end
		if (S != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					s_check ( .error(1'b1) );
		end
		if (K != 32)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					k_check ( .error(1'b1) );
		end
		if (SCR != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					scr_check ( .error(1'b1) );
		end
		if (CS != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					cs_check ( .error(1'b1) );
		end
		if (CF != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					cf_check ( .error(1'b1) );
		end
		if (HD != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					hd_check ( .error(1'b1) );
		end
		if (ECC_EN != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					ecc_en_check ( .error(1'b1) );
		end
		if (DLB_TEST != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					dlb_test_check ( .error(1'b1) );
		end
		if (PHADJ != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					phadj_check ( .error(1'b1) );
		end
		if (ADJCNT != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					adjcnt_check ( .error(1'b1) );
		end
		if (ADJDIR != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					adjdir_check ( .error(1'b1) );
		end
		if (OPTIMIZE != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					optimize_check ( .error(1'b1) );
		end
		if (DID != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					did_check ( .error(1'b1) );
		end
		if (BID != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					bid_check ( .error(1'b1) );
		end
		if (LID0 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					lid0_check ( .error(1'b1) );
		end
		if (FCHK0 != 65)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					fchk0_check ( .error(1'b1) );
		end
		if (LID1 != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					lid1_check ( .error(1'b1) );
		end
		if (FCHK1 != 66)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					fchk1_check ( .error(1'b1) );
		end
		if (LID2 != 2)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					lid2_check ( .error(1'b1) );
		end
		if (FCHK2 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					fchk2_check ( .error(1'b1) );
		end
		if (LID3 != 3)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					lid3_check ( .error(1'b1) );
		end
		if (FCHK3 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					fchk3_check ( .error(1'b1) );
		end
		if (LID4 != 4)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					lid4_check ( .error(1'b1) );
		end
		if (FCHK4 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					fchk4_check ( .error(1'b1) );
		end
		if (LID5 != 5)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					lid5_check ( .error(1'b1) );
		end
		if (FCHK5 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					fchk5_check ( .error(1'b1) );
		end
		if (LID6 != 6)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					lid6_check ( .error(1'b1) );
		end
		if (FCHK6 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					fchk6_check ( .error(1'b1) );
		end
		if (LID7 != 7)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					lid7_check ( .error(1'b1) );
		end
		if (FCHK7 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					fchk7_check ( .error(1'b1) );
		end
		if (JESDV != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					jesdv_check ( .error(1'b1) );
		end
		if (PMA_WIDTH != 32)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					pma_width_check ( .error(1'b1) );
		end
		if (SER_SIZE != 4)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					ser_size_check ( .error(1'b1) );
		end
		if (FK != 64)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					fk_check ( .error(1'b1) );
		end
		if (RES1 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					res1_check ( .error(1'b1) );
		end
		if (RES2 != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					res2_check ( .error(1'b1) );
		end
		if (BIT_REVERSAL != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					bit_reversal_check ( .error(1'b1) );
		end
		if (BYTE_REVERSAL != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					byte_reversal_check ( .error(1'b1) );
		end
		if (ALIGNMENT_PATTERN != 658812)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					alignment_pattern_check ( .error(1'b1) );
		end
		if (PULSE_WIDTH != 2)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					pulse_width_check ( .error(1'b1) );
		end
		if (LS_FIFO_DEPTH != 32)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					ls_fifo_depth_check ( .error(1'b1) );
		end
		if (LS_FIFO_WIDTHU != 5)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					ls_fifo_widthu_check ( .error(1'b1) );
		end
		if (UNUSED_TX_PARALLEL_WIDTH != 8)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					unused_tx_parallel_width_check ( .error(1'b1) );
		end
		if (UNUSED_RX_PARALLEL_WIDTH != 8)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					unused_rx_parallel_width_check ( .error(1'b1) );
		end
		if (XCVR_PLL_LOCKED_WIDTH != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					xcvr_pll_locked_width_check ( .error(1'b1) );
		end
	endgenerate

	altera_jesd204_rx_base #(
		.SUBCLASSV      (1),
		.L              (2),
		.M              (2),
		.F              (2),
		.N              (14),
		.N_PRIME        (16),
		.S              (1),
		.K              (32),
		.SCR            (1),
		.CS             (0),
		.CF             (0),
		.HD             (0),
		.ECC_EN         (1),
		.DLB_TEST       (0),
		.JESDV          (1),
		.FK             (64),
		.BIT_REVERSAL   (0),
		.BYTE_REVERSAL  (0),
		.PULSE_WIDTH    (2),
		.LS_FIFO_DEPTH  (32),
		.LS_FIFO_WIDTHU (5)
	) inst_rx (
		.rxlink_clk                 (rxlink_clk),                                //                rxlink_clk.clk
		.rxlink_rst_n               (rxlink_rst_n_reset_n),                      //              rxlink_rst_n.reset_n
		.jesd204_rx_avs_clk         (jesd204_rx_avs_clk),                        //        jesd204_rx_avs_clk.clk
		.jesd204_rx_avs_rst_n       (jesd204_rx_avs_rst_n),                      //      jesd204_rx_avs_rst_n.reset_n
		.jesd204_rx_avs_chipselect  (jesd204_rx_avs_chipselect),                 //            jesd204_rx_avs.chipselect
		.jesd204_rx_avs_address     (jesd204_rx_avs_address),                    //                          .address
		.jesd204_rx_avs_read        (jesd204_rx_avs_read),                       //                          .read
		.jesd204_rx_avs_readdata    (jesd204_rx_avs_readdata),                   //                          .readdata
		.jesd204_rx_avs_waitrequest (jesd204_rx_avs_waitrequest),                //                          .waitrequest
		.jesd204_rx_avs_write       (jesd204_rx_avs_write),                      //                          .write
		.jesd204_rx_avs_writedata   (jesd204_rx_avs_writedata),                  //                          .writedata
		.jesd204_rx_link_data       (jesd204_rx_link_data),                      //                   avst_rx.data
		.jesd204_rx_link_valid      (jesd204_rx_link_valid),                     //                          .valid
		.jesd204_rx_link_ready      (jesd204_rx_link_ready),                     //                          .ready
		.sof                        (rx_sof),                                    //                       sof.export
		.somf                       (rx_somf),                                   //                      somf.export
		.alldev_lane_aligned        (alldev_lane_aligned),                       //       alldev_lane_aligned.export
		.dev_lane_aligned           (dev_lane_aligned),                          //          dev_lane_aligned.export
		.dev_sync_n                 (rx_dev_sync_n),                             //                dev_sync_n.export
		.sysref                     (rx_sysref),                                 //                    sysref.export
		.jesd204_rx_int             (jesd204_rx_int),                            //            jesd204_rx_int.export
		.csr_rx_testmode            (csr_rx_testmode),                           //           csr_rx_testmode.export
		.csr_f                      (rx_csr_f),                                  //                     csr_f.export
		.csr_k                      (rx_csr_k),                                  //                     csr_k.export
		.csr_l                      (rx_csr_l),                                  //                     csr_l.export
		.csr_m                      (rx_csr_m),                                  //                     csr_m.export
		.csr_n                      (rx_csr_n),                                  //                     csr_n.export
		.csr_s                      (rx_csr_s),                                  //                     csr_s.export
		.csr_cf                     (rx_csr_cf),                                 //                    csr_cf.export
		.csr_cs                     (rx_csr_cs),                                 //                    csr_cs.export
		.csr_hd                     (rx_csr_hd),                                 //                    csr_hd.export
		.csr_np                     (rx_csr_np),                                 //                    csr_np.export
		.csr_byte_reversal          (inst_rx_csr_byte_reversal_export),          //         csr_byte_reversal.export
		.csr_bit_reversal           (inst_rx_csr_bit_reversal_export),           //          csr_bit_reversal.export
		.csr_lane_polarity          (inst_rx_csr_lane_polarity_export),          //         csr_lane_polarity.export
		.csr_lane_powerdown         (rx_csr_lane_powerdown),                     //        csr_lane_powerdown.export
		.jesd204_rx_frame_error     (jesd204_rx_frame_error),                    //    jesd204_rx_frame_error.export
		.jesd204_rx_pcs_data        (inst_phy_jesd204_rx_pcs_data_export),       //       jesd204_rx_pcs_data.export
		.jesd204_rx_pcs_data_valid  (inst_phy_jesd204_rx_pcs_data_valid_export), // jesd204_rx_pcs_data_valid.export
		.jesd204_rx_pcs_kchar_data  (inst_phy_jesd204_rx_pcs_kchar_data_export), // jesd204_rx_pcs_kchar_data.export
		.jesd204_rx_pcs_errdetect   (inst_phy_jesd204_rx_pcs_errdetect_export),  //  jesd204_rx_pcs_errdetect.export
		.jesd204_rx_pcs_disperr     (inst_phy_jesd204_rx_pcs_disperr_export),    //    jesd204_rx_pcs_disperr.export
		.patternalign_en            (inst_rx_patternalign_en_export),            //           patternalign_en.export
		.phy_csr_rx_pcfifo_empty    (inst_phy_phy_csr_rx_pcfifo_empty_export),   //   phy_csr_rx_pcfifo_empty.export
		.phy_csr_rx_pcfifo_full     (inst_phy_phy_csr_rx_pcfifo_full_export),    //    phy_csr_rx_pcfifo_full.export
		.phy_csr_rx_cal_busy        (rx_cal_busy),                               //       phy_csr_rx_cal_busy.export
		.phy_csr_rx_locked_to_data  (rx_islockedtodata),                         // phy_csr_rx_locked_to_data.export
		.jesd204_rx_dlb_data        (jesd204_rx_dlb_data),                       //       jesd204_rx_dlb_data.export
		.jesd204_rx_dlb_data_valid  (jesd204_rx_dlb_data_valid),                 // jesd204_rx_dlb_data_valid.export
		.jesd204_rx_dlb_kchar_data  (jesd204_rx_dlb_kchar_data),                 // jesd204_rx_dlb_kchar_data.export
		.jesd204_rx_dlb_errdetect   (jesd204_rx_dlb_errdetect),                  //  jesd204_rx_dlb_errdetect.export
		.jesd204_rx_dlb_disperr     (jesd204_rx_dlb_disperr)                     //    jesd204_rx_dlb_disperr.export
	);

	altera_jesd204_tx_base #(
		.DEVICE_FAMILY ("Arria V"),
		.SUBCLASSV     (1),
		.L             (2),
		.M             (2),
		.F             (2),
		.N             (14),
		.N_PRIME       (16),
		.S             (1),
		.K             (32),
		.SCR           (1),
		.CS            (0),
		.CF            (0),
		.HD            (0),
		.ADJCNT        (0),
		.ADJDIR        (0),
		.PHADJ         (0),
		.OPTIMIZE      (0),
		.DID           (0),
		.BID           (0),
		.LID0          (0),
		.FCHK0         (65),
		.LID1          (1),
		.FCHK1         (66),
		.LID2          (2),
		.FCHK2         (0),
		.LID3          (3),
		.FCHK3         (0),
		.LID4          (4),
		.FCHK4         (0),
		.LID5          (5),
		.FCHK5         (0),
		.LID6          (6),
		.FCHK6         (0),
		.LID7          (7),
		.FCHK7         (0),
		.JESDV         (1),
		.PMA_WIDTH     (32),
		.SER_SIZE      (4),
		.FK            (64),
		.RES1          (0),
		.RES2          (0),
		.BIT_REVERSAL  (0),
		.BYTE_REVERSAL (0),
		.PULSE_WIDTH   (2)
	) inst_tx (
		.txlink_clk                 (txlink_clk),                              //                txlink_clk.clk
		.txlink_rst_n               (txlink_rst_n_reset_n),                    //              txlink_rst_n.reset_n
		.jesd204_tx_avs_clk         (jesd204_tx_avs_clk),                      //        jesd204_tx_avs_clk.clk
		.jesd204_tx_avs_rst_n       (jesd204_tx_avs_rst_n),                    //      jesd204_tx_avs_rst_n.reset_n
		.jesd204_tx_avs_chipselect  (jesd204_tx_avs_chipselect),               //            jesd204_tx_avs.chipselect
		.jesd204_tx_avs_address     (jesd204_tx_avs_address),                  //                          .address
		.jesd204_tx_avs_read        (jesd204_tx_avs_read),                     //                          .read
		.jesd204_tx_avs_readdata    (jesd204_tx_avs_readdata),                 //                          .readdata
		.jesd204_tx_avs_waitrequest (jesd204_tx_avs_waitrequest),              //                          .waitrequest
		.jesd204_tx_avs_write       (jesd204_tx_avs_write),                    //                          .write
		.jesd204_tx_avs_writedata   (jesd204_tx_avs_writedata),                //                          .writedata
		.jesd204_tx_link_data       (jesd204_tx_link_data),                    //                   avst_tx.data
		.jesd204_tx_link_valid      (jesd204_tx_link_valid),                   //                          .valid
		.jesd204_tx_link_ready      (jesd204_tx_link_ready),                   //                          .ready
		.dev_sync_n                 (tx_dev_sync_n),                           //                dev_sync_n.export
		.mdev_sync_n                (mdev_sync_n),                             //               mdev_sync_n.export
		.sysref                     (tx_sysref),                               //                    sysref.export
		.sync_n                     (sync_n),                                  //                    sync_n.export
		.jesd204_tx_int             (jesd204_tx_int),                          //            jesd204_tx_int.export
		.csr_hd                     (tx_csr_hd),                               //                    csr_hd.export
		.csr_cs                     (tx_csr_cs),                               //                    csr_cs.export
		.csr_l                      (tx_csr_l),                                //                     csr_l.export
		.csr_k                      (tx_csr_k),                                //                     csr_k.export
		.csr_n                      (tx_csr_n),                                //                     csr_n.export
		.csr_np                     (tx_csr_np),                               //                    csr_np.export
		.csr_s                      (tx_csr_s),                                //                     csr_s.export
		.csr_cf                     (tx_csr_cf),                               //                    csr_cf.export
		.csr_f                      (tx_csr_f),                                //                     csr_f.export
		.csr_m                      (tx_csr_m),                                //                     csr_m.export
		.csr_lane_powerdown         (tx_csr_lane_powerdown),                   //        csr_lane_powerdown.export
		.csr_lane_polarity          (inst_tx_csr_lane_polarity_export),        //         csr_lane_polarity.export
		.csr_bit_reversal           (inst_tx_csr_bit_reversal_export),         //          csr_bit_reversal.export
		.csr_byte_reversal          (inst_tx_csr_byte_reversal_export),        //         csr_byte_reversal.export
		.jesd204_tx_frame_error     (jesd204_tx_frame_error),                  //    jesd204_tx_frame_error.export
		.jesd204_tx_frame_ready     (jesd204_tx_frame_ready),                  //    jesd204_tx_frame_ready.export
		.jesd204_tx_pcs_data        (jesd204_tx_dlb_data),                     //       jesd204_tx_pcs_data.export
		.jesd204_tx_pcs_kchar_data  (jesd204_tx_dlb_kchar_data),               // jesd204_tx_pcs_kchar_data.export
		.phy_csr_pll_locked         (pll_locked),                              //        phy_csr_pll_locked.export
		.phy_csr_tx_cal_busy        (tx_cal_busy),                             //       phy_csr_tx_cal_busy.export
		.phy_csr_tx_pcfifo_full     (inst_phy_phy_csr_tx_pcfifo_full_export),  //    phy_csr_tx_pcfifo_full.export
		.phy_csr_tx_pcfifo_empty    (inst_phy_phy_csr_tx_pcfifo_empty_export), //   phy_csr_tx_pcfifo_empty.export
		.phy_tx_elecidle            (inst_tx_phy_tx_elecidle_export),          //           phy_tx_elecidle.export
		.csr_tx_testmode            (csr_tx_testmode),                         //           csr_tx_testmode.export
		.csr_tx_testpattern_a       (csr_tx_testpattern_a),                    //      csr_tx_testpattern_a.export
		.csr_tx_testpattern_b       (csr_tx_testpattern_b),                    //      csr_tx_testpattern_b.export
		.csr_tx_testpattern_c       (csr_tx_testpattern_c),                    //      csr_tx_testpattern_c.export
		.csr_tx_testpattern_d       (csr_tx_testpattern_d)                     //      csr_tx_testpattern_d.export
	);

	altera_jesd204_inst_phy #(
		.DEVICE_FAMILY            ("Arria V"),
		.L                        (2),
		.PCS_CONFIG               ("JESD_PCS_CFG1"),
		.PMA_WIDTH                (32),
		.SER_SIZE                 (4),
		.ALIGNMENT_PATTERN        (658812),
		.UNUSED_TX_PARALLEL_WIDTH (8),
		.UNUSED_RX_PARALLEL_WIDTH (8),
		.XCVR_PLL_LOCKED_WIDTH    (1)
	) inst_phy (
		.tx_pll_ref_clk            (tx_pll_ref_clk),                            //            tx_pll_ref_clk.clk
		.txlink_clk                (txlink_clk),                                //                txlink_clk.clk
		.txlink_rst_n              (txlink_rst_n_reset_n),                      //              txlink_rst_n.reset_n
		.jesd204_tx_pcs_data       (jesd204_tx_dlb_data),                       //       jesd204_tx_pcs_data.export
		.jesd204_tx_pcs_kchar_data (jesd204_tx_dlb_kchar_data),                 // jesd204_tx_pcs_kchar_data.export
		.tx_csr_lane_polarity      (inst_tx_csr_lane_polarity_export),          //      tx_csr_lane_polarity.export
		.tx_csr_bit_reversal       (inst_tx_csr_bit_reversal_export),           //       tx_csr_bit_reversal.export
		.tx_csr_byte_reversal      (inst_tx_csr_byte_reversal_export),          //      tx_csr_byte_reversal.export
		.phy_csr_pll_locked        (pll_locked),                                //        phy_csr_pll_locked.export
		.phy_csr_tx_cal_busy       (tx_cal_busy),                               //       phy_csr_tx_cal_busy.export
		.phy_tx_elecidle           (inst_tx_phy_tx_elecidle_export),            //           phy_tx_elecidle.export
		.phy_csr_tx_pcfifo_full    (inst_phy_phy_csr_tx_pcfifo_full_export),    //    phy_csr_tx_pcfifo_full.export
		.phy_csr_tx_pcfifo_empty   (inst_phy_phy_csr_tx_pcfifo_empty_export),   //   phy_csr_tx_pcfifo_empty.export
		.rx_pll_ref_clk            (rx_pll_ref_clk),                            //            rx_pll_ref_clk.clk
		.rxlink_clk                (rxlink_clk),                                //                rxlink_clk.clk
		.rxlink_rst_n              (rxlink_rst_n_reset_n),                      //              rxlink_rst_n.reset_n
		.rx_csr_lane_polarity      (inst_rx_csr_lane_polarity_export),          //      rx_csr_lane_polarity.export
		.rx_csr_bit_reversal       (inst_rx_csr_bit_reversal_export),           //       rx_csr_bit_reversal.export
		.rx_csr_byte_reversal      (inst_rx_csr_byte_reversal_export),          //      rx_csr_byte_reversal.export
		.patternalign_en           (inst_rx_patternalign_en_export),            //           patternalign_en.export
		.jesd204_rx_pcs_data       (inst_phy_jesd204_rx_pcs_data_export),       //       jesd204_rx_pcs_data.export
		.jesd204_rx_pcs_data_valid (inst_phy_jesd204_rx_pcs_data_valid_export), // jesd204_rx_pcs_data_valid.export
		.jesd204_rx_pcs_kchar_data (inst_phy_jesd204_rx_pcs_kchar_data_export), // jesd204_rx_pcs_kchar_data.export
		.jesd204_rx_pcs_errdetect  (inst_phy_jesd204_rx_pcs_errdetect_export),  //  jesd204_rx_pcs_errdetect.export
		.jesd204_rx_pcs_disperr    (inst_phy_jesd204_rx_pcs_disperr_export),    //    jesd204_rx_pcs_disperr.export
		.phy_csr_rx_locked_to_data (rx_islockedtodata),                         // phy_csr_rx_locked_to_data.export
		.phy_csr_rx_cal_busy       (rx_cal_busy),                               //       phy_csr_rx_cal_busy.export
		.phy_csr_rx_pcfifo_full    (inst_phy_phy_csr_rx_pcfifo_full_export),    //    phy_csr_rx_pcfifo_full.export
		.phy_csr_rx_pcfifo_empty   (inst_phy_phy_csr_rx_pcfifo_empty_export),   //   phy_csr_rx_pcfifo_empty.export
		.tx_serial_data            (tx_serial_data),                            //            tx_serial_data.tx_serial_data
		.pll_powerdown             (pll_powerdown),                             //             pll_powerdown.pll_powerdown
		.tx_analogreset            (tx_analogreset),                            //            tx_analogreset.tx_analogreset
		.tx_digitalreset           (tx_digitalreset),                           //           tx_digitalreset.tx_digitalreset
		.txphy_clk                 (txphy_clk),                                 //                 txphy_clk.tx_std_clkout
		.rx_serial_data            (rx_serial_data),                            //            rx_serial_data.rx_serial_data
		.rx_analogreset            (rx_analogreset),                            //            rx_analogreset.rx_analogreset
		.rx_digitalreset           (rx_digitalreset),                           //           rx_digitalreset.rx_digitalreset
		.reconfig_to_xcvr          (reconfig_to_xcvr),                          //          reconfig_to_xcvr.reconfig_to_xcvr
		.reconfig_from_xcvr        (reconfig_from_xcvr),                        //        reconfig_from_xcvr.reconfig_from_xcvr
		.rxphy_clk                 (rxphy_clk),                                 //                 rxphy_clk.rx_std_clkout
		.rx_seriallpbken           (rx_seriallpbken)                            //           rx_seriallpbken.rx_seriallpbken
	);

endmodule
